{{- if .Values.rbac.pspEnabled }}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ template "aws-node-termination-handler.fullname" . }}
  labels:
{{ include "aws-node-termination-handler.labels" . | indent 4 }}
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
spec:
  privileged: false
  hostIPC: false
  hostNetwork: {{ .Values.useHostNetwork }}
  hostPID: false
{{- if and .Values.rbac.pspEnabled .Values.enablePrometheusServer }}
  hostPorts:
  - min: {{ .Values.prometheusServerPort }}
    max: {{ .Values.prometheusServerPort }}
{{- end }}
  readOnlyRootFilesystem: false
  allowPrivilegeEscalation: false
  allowedCapabilities:
    - '*'
  fsGroup:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
    - '*'
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "aws-node-termination-handler.fullname" . }}-psp
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "aws-node-termination-handler.labels" . | indent 4 }}
rules:
  - apiGroups: ['policy']
    resources: ['podsecuritypolicies']
    verbs:     ['use']
    resourceNames:
      - {{ template "aws-node-termination-handler.fullname" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "aws-node-termination-handler.fullname" . }}-psp
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "aws-node-termination-handler.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "aws-node-termination-handler.fullname" . }}-psp
subjects:
  - kind: ServiceAccount
    name: {{ template "aws-node-termination-handler.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
