{{- if .Values.regularPodTest.create -}}
{{- $isWindows := (contains "windows" .Values.targetNodeOs) -}}
{{- $k8sVersion := printf "%s.%s" .Capabilities.KubeVersion.Major .Capabilities.KubeVersion.Minor | replace "+" "" -}}
{{- $osSelector := (semverCompare "<1.14" $k8sVersion | ternary "beta.kubernetes.io/os" "kubernetes.io/os") -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.regularPodTest.label }}
  labels:
    app: {{ .Values.regularPodTest.label }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.regularPodTest.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.regularPodTest.label }}
    spec:
      nodeSelector:
        {{ $osSelector }}: {{ $isWindows | ternary "windows" "linux" }}
      {{- if (not $isWindows) }}
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      {{- end }}
      containers:
      - name: {{ .Values.regularPodTest.label }}
        image: {{ .Values.webhookTestProxy.image.repository }}:{{ .Values.webhookTestProxy.image.tag }}
        imagePullPolicy: {{ .Values.webhookTestProxy.image.pullPolicy }}
        env:
        - name: PORT
          value: {{ .Values.regularPodTest.port | quote }}
{{- end -}}
