{{- if .Values.regularPodTest.create -}}
{{- $isWindows := (contains "windows" .Values.targetNodeOs) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.regularPodTest.label }}
  labels:
    app: {{ .Values.regularPodTest.label }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.regularPodTest.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.regularPodTest.label }}
    spec:
      nodeSelector:
        kubernetes.io/os: {{ $isWindows | ternary "windows" "linux" }}
      {{- if (not $isWindows) }}
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      {{- end }}
      serviceAccountName: {{ template "ec2-metadata-test-proxy.serviceAccountName" . }}
      containers:
      - name: {{ .Values.regularPodTest.label }}
        image: {{ .Values.ec2MetadataTestProxy.image.repository }}:{{ .Values.ec2MetadataTestProxy.image.tag }}
        imagePullPolicy: {{ .Values.ec2MetadataTestProxy.image.pullPolicy }}
        env:
        - name: PORT
          value: {{ .Values.regularPodTest.port | quote }}
{{- end -}}
