apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
commonLabels:
  app: node-termination-handler
resources:
- cluster-role.yaml
- service-account.yaml
- cluster-role-binding.yaml
- daemonset.yaml